# Regression

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
            

In [ ]:
from sklearn.datasets import load_boston
data = load_boston()

In [ ]:
x = data.data
y = data.target

In [ ]:
x.shape

(506, 13)

In [ ]:
y.shape

(506,)

In [ ]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

In [ ]:
x_train

array([[1.78667e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.93740e+02, 2.17800e+01],
       [7.90410e-01, 0.00000e+00, 9.90000e+00, ..., 1.84000e+01,
        3.96900e+02, 5.98000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.63430e+02, 4.59000e+00],
       ...,
       [2.83920e-01, 0.00000e+00, 7.38000e+00, ..., 1.96000e+01,
        3.91130e+02, 1.17400e+01],
       [3.57800e-02, 2.00000e+01, 3.33000e+00, ..., 1.49000e+01,
        3.87310e+02, 3.76000e+00],
       [2.11240e-01, 1.25000e+01, 7.87000e+00, ..., 1.52000e+01,
        3.86630e+02, 2.99300e+01]])

In [ ]:
y_test

array([34.6, 31.5, 20.6, 14.5, 16.2, 22.3, 22.8, 24.4, 19.8, 16.7, 23.2,
       15.1, 21. , 18.9, 48.5, 24.1, 22.5, 16.1, 30.3, 50. , 33.8, 10.4,
       20.4, 14.2, 10.5, 12.7, 24.5, 16.7, 20.1, 17.1, 18.4, 24.3, 50. ,
       23.8, 30.7, 33.4, 15. , 10.9, 19.1, 21. , 22.9, 22.4, 19. , 19.3,
       27. , 27.1, 19.1, 15.4, 19.1, 13.5, 20.9, 19.3, 20.5, 26.2, 12. ,
       19.7, 29.6, 34.9,  8.3, 21.2, 14.5, 27.5, 19.4, 32.7, 21.1, 28.1,
       17.4, 30.1, 21.4, 20.9, 10.9, 21.7,  8.8, 15.2, 26.6,  8.7, 24.7,
       38.7,  6.3, 22.6, 43.8, 50. , 14.5, 11.7, 12.5, 13.6, 21.5, 19.1,
        9.5, 17.2, 29.8, 22.6, 21.6, 22.2, 27.1, 17. , 22. , 50. ,  7.2,
       50. , 14. , 11. ])

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred= lr.predict(x_test)
y_pred

array([34.4081095 , 31.18524626, 22.31286141, 17.88613877, 20.43572131,
       26.14444413, 26.21920244, 23.57978445, 22.41577853, 19.51182817,
       26.86691495, 17.20411302, 20.68511041, 15.67921778, 41.69912781,
       20.2946735 , 28.99258631, 19.06413492, 32.48035595, 41.13627224,
       34.64732462, 16.38997909, 20.42215729, 18.05324255, 13.38743087,
       12.64800748, 27.45930237, 20.30199107, 18.78954741, 20.24950994,
       15.60161419, 24.38040555, 38.95651978, 24.7184131 , 31.26791961,
       28.26279775, 15.84707127, 14.76661568, 16.79024244, 23.23674899,
       22.85417065, 23.48976177, 14.16818173, 21.42613087, 32.38362329,
       26.7881669 , 19.37574824, 15.27894103, 17.21175121, 12.91591919,
       21.84063224, 20.25050371, 23.65622638, 23.9608324 , 11.94749102,
       14.49718052, 24.69872363, 34.18169066, 10.30437821, 21.04686616,
       17.96204214, 19.76593459, 17.45231513, 29.982971  , 20.73183476,
       25.24657823, 15.81416285, 24.96705225, 22.1298931 , 20.77

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_squared_error(y_test,y_pred)

23.616994100563623

In [ ]:
mean_absolute_error(y_test,y_pred)

3.248482087616415

In [ ]:
r2_score(y_test,y_pred)

0.7555033086871306

In [ ]:
from sklearn.linear_model import HuberRegressor
hr = HuberRegressor()

In [ ]:
hr.fit(x_train,y_train)

C:\Users\MSCIT\anaconda3\lib\site-packages\sklearn\linear_model\_huber.py:296: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


HuberRegressor()

In [ ]:
pred= hr.predict(x_test)
pred

array([33.09929104, 29.66653005, 23.20144106, 18.84384408, 19.46242669,
       23.14536336, 25.85717218, 23.61009963, 23.07457116, 19.16417386,
       25.20716094, 16.46427496, 22.97698688, 17.60475209, 41.35707501,
       21.55749226, 26.60621456, 16.62737777, 31.01514527, 38.52144433,
       34.43731926, 12.60266881, 19.13146707, 17.38980324, 13.68591651,
       10.916513  , 28.02464524, 20.40356029, 16.41926289, 19.63194138,
       16.71262061, 22.48738694, 40.56322537, 24.94498477, 31.63708457,
       28.97055331,  6.25989585,  9.92221548, 15.61778352, 22.57206452,
       21.50549921, 25.65925167, 11.36426547, 20.07334166, 25.46076612,
       24.69949284, 18.14978232, 16.99370924, 15.36256844, 10.63955792,
       21.3406359 , 20.77446865, 22.23426934, 25.25524561,  9.8447916 ,
       15.41223803, 26.45021571, 34.50183553,  7.84418843, 20.27038508,
       14.68446134, 17.96414546, 17.57003181, 30.31712144, 22.14226886,
       25.23885042, 17.32420117, 26.28397019, 21.71132125, 19.84

In [ ]:
mean_squared_error(y_test,pred)

27.87864943923398

In [ ]:
mean_absolute_error(y_test,pred)

3.2734822539829507

In [ ]:
r2_score(y_test,pred)*100

71.13842042243039

# Classification

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.shape

(768, 9)

In [ ]:
x = df.iloc[:,0:8]
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
y = df.iloc[:,-1:]
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [ ]:
import keras

In [ ]:
import tensorflow

In [ ]:
from keras.layers import Dense
from keras.models import Sequential

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(units=30,input_dim=8,activation='relu'))
model.add(Dense(units=20,activation='relu'))
model.add(Dense(units=10,activation='relu'))
model.add(Dense(units=1,activation='sigmoid'))

In [ ]:
#binary_crossentropy= binary classification  #Categorical_crossentropy= Multiclass classification 
#optimizer works on Sgd stochastic gradient desecent, to find the minimum value
#metrics = how much decrease in the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [ ]:
model.fit(x,y,epochs=1000,batch_size=32)

Epoch 1/1000
24/24 [==============================] - 1s 1ms/step - loss: 0.6747 - accuracy: 0.8125
Epoch 2/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.6285 - accuracy: 0.8516
Epoch 3/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.5761 - accuracy: 0.8359
Epoch 4/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.5173 - accuracy: 0.8372
Epoch 5/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.4478 - accuracy: 0.8464
Epoch 6/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.4056 - accuracy: 0.8542
Epoch 7/1000
24/24 [==============================] - 0s 2ms/step - loss: 0.3825 - accuracy: 0.8385
Epoch 8/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3746 - accuracy: 0.8411
Epoch 9/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3725 - accuracy: 0.8424
Epoch 10/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3651 - accuracy: 0.8424

24/24 [==============================] - 0s 1ms/step - loss: 0.2921 - accuracy: 0.8802
Epoch 83/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3131 - accuracy: 0.8607
Epoch 84/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2961 - accuracy: 0.8698
Epoch 85/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3096 - accuracy: 0.8672
Epoch 86/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3089 - accuracy: 0.8737
Epoch 87/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3393 - accuracy: 0.8490
Epoch 88/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3186 - accuracy: 0.8555
Epoch 89/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8646
Epoch 90/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2947 - accuracy: 0.8698
Epoch 91/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8672
Epoc

24/24 [==============================] - 0s 1ms/step - loss: 0.2860 - accuracy: 0.8815
Epoch 163/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8685
Epoch 164/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2943 - accuracy: 0.8724
Epoch 165/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2971 - accuracy: 0.8685
Epoch 166/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2823 - accuracy: 0.8724
Epoch 167/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.8724
Epoch 168/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2850 - accuracy: 0.8867
Epoch 169/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2903 - accuracy: 0.8763
Epoch 170/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2855 - accuracy: 0.8789
Epoch 171/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2859 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2810 - accuracy: 0.8854
Epoch 243/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2986 - accuracy: 0.8685
Epoch 244/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2839 - accuracy: 0.8776
Epoch 245/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2913 - accuracy: 0.8724
Epoch 246/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2836 - accuracy: 0.8815
Epoch 247/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2878 - accuracy: 0.8763
Epoch 248/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2962 - accuracy: 0.8620
Epoch 249/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2811 - accuracy: 0.8763
Epoch 250/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2760 - accuracy: 0.8867
Epoch 251/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2734 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.3079 - accuracy: 0.8698
Epoch 323/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2969 - accuracy: 0.8737
Epoch 324/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2768 - accuracy: 0.8789
Epoch 325/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2688 - accuracy: 0.8906
Epoch 326/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2912 - accuracy: 0.8685
Epoch 327/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.8646
Epoch 328/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8659
Epoch 329/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2673 - accuracy: 0.8893
Epoch 330/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2982 - accuracy: 0.8633
Epoch 331/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2764 - accuracy: 0.8776
Epoch 403/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2772 - accuracy: 0.8672
Epoch 404/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8698
Epoch 405/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3213 - accuracy: 0.8633
Epoch 406/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3096 - accuracy: 0.8672
Epoch 407/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2729 - accuracy: 0.8854
Epoch 408/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2635 - accuracy: 0.8867
Epoch 409/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2586 - accuracy: 0.8867
Epoch 410/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2746 - accuracy: 0.8789
Epoch 411/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2675 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2660 - accuracy: 0.8893
Epoch 483/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2607 - accuracy: 0.8841
Epoch 484/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2638 - accuracy: 0.8893
Epoch 485/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2743 - accuracy: 0.8841
Epoch 486/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2539 - accuracy: 0.8958
Epoch 487/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2515 - accuracy: 0.8958
Epoch 488/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2637 - accuracy: 0.8841
Epoch 489/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2654 - accuracy: 0.8841
Epoch 490/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2613 - accuracy: 0.8893
Epoch 491/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2596 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2702 - accuracy: 0.8893
Epoch 563/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2722 - accuracy: 0.8802
Epoch 564/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2550 - accuracy: 0.8893
Epoch 565/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2549 - accuracy: 0.8932
Epoch 566/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2514 - accuracy: 0.8945
Epoch 567/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2424 - accuracy: 0.8984
Epoch 568/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2690 - accuracy: 0.8815
Epoch 569/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8698
Epoch 570/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2665 - accuracy: 0.8893
Epoch 571/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2639 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2641 - accuracy: 0.8828
Epoch 643/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2700 - accuracy: 0.8776
Epoch 644/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2676 - accuracy: 0.8880
Epoch 645/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2705 - accuracy: 0.8750
Epoch 646/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2536 - accuracy: 0.8971
Epoch 647/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2456 - accuracy: 0.8906
Epoch 648/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2422 - accuracy: 0.8958
Epoch 649/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8542
Epoch 650/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3146 - accuracy: 0.8581
Epoch 651/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2922 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2410 - accuracy: 0.8958
Epoch 723/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2430 - accuracy: 0.9010
Epoch 724/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2517 - accuracy: 0.8880
Epoch 725/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2707 - accuracy: 0.8776
Epoch 726/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2586 - accuracy: 0.8724
Epoch 727/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2611 - accuracy: 0.8880
Epoch 728/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8490
Epoch 729/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2590 - accuracy: 0.8893
Epoch 730/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2531 - accuracy: 0.8932
Epoch 731/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2301 - accuracy: 0.8997
Epoch 803/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2422 - accuracy: 0.8893
Epoch 804/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2387 - accuracy: 0.8945
Epoch 805/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2421 - accuracy: 0.9023
Epoch 806/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3466 - accuracy: 0.8529
Epoch 807/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3431 - accuracy: 0.8529
Epoch 808/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.3471 - accuracy: 0.8633
Epoch 809/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2670 - accuracy: 0.8906
Epoch 810/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2619 - accuracy: 0.8815
Epoch 811/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2501 - accuracy: 0.

24/24 [==============================] - 0s 1ms/step - loss: 0.2423 - accuracy: 0.9010
Epoch 883/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2435 - accuracy: 0.8828
Epoch 884/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2589 - accuracy: 0.8971
Epoch 885/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2809 - accuracy: 0.8698
Epoch 886/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2410 - accuracy: 0.9023
Epoch 887/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2326 - accuracy: 0.9089
Epoch 888/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2481 - accuracy: 0.8867
Epoch 889/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2357 - accuracy: 0.8971
Epoch 890/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2577 - accuracy: 0.8971
Epoch 891/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2614 - accuracy: 0.

24/24 [==============================] - 0s 2ms/step - loss: 0.2363 - accuracy: 0.9062
Epoch 963/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2374 - accuracy: 0.8984
Epoch 964/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2442 - accuracy: 0.8932
Epoch 965/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2526 - accuracy: 0.8867
Epoch 966/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2622 - accuracy: 0.8880
Epoch 967/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2451 - accuracy: 0.9010
Epoch 968/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2209 - accuracy: 0.9193
Epoch 969/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2565 - accuracy: 0.8932
Epoch 970/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2545 - accuracy: 0.8893
Epoch 971/1000
24/24 [==============================] - 0s 1ms/step - loss: 0.2706 - accuracy: 0.